name    'zleslie-poudriere'
version '0.0.9'
source 'git://github.com/xaque208/puppet-poudriere.git'
author 'zleslie'
license 'Apache License Version 2.0'
summary 'A module to manage the PkgNG build system'
description 'Manage the FreeBSD PkgNG build system with puppet'
project_page 'https://github.com/xaque208/puppet-poudriere'
